# Generated by Django 4.2.2 on 2023-06-22 17:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("longitude", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "email_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "validation_stage",
                    models.CharField(
                        choices=[
                            ("Approved", "Approved"),
                            ("To be reviewed", "To be reviewed"),
                            ("Rejected", "Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
        ),
    ]
