# Generated by Django 4.2.2 on 2023-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("longitude", models.CharField(blank=True, max_length=255, null=True)),
                ("latitude", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "email_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("timestamp", models.TextField(default="1687282383.90331")),
                (
                    "validation_stage",
                    models.CharField(
                        choices=[
                            ("Approved", "approved"),
                            ("To be reviewed", "to_be_reviewed"),
                            ("Rejected", "rejected"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
