# Generated by Django 4.2.2 on 2023-06-22 17:14

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Articles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[apps.utils.validate_url],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("authors", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "publication_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("article_content", models.TextField(blank=True, null=True)),
                ("timestamp", models.TextField(default="1687454080.1471229")),
                (
                    "validation_stage",
                    models.CharField(
                        choices=[
                            ("Approved", "approved"),
                            ("To be reviewed", "to_be_reviewed"),
                            ("Rejected", "rejected"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
